apiVersion: v1
kind: Secret

metadata:
  name: "{{ .Values.appName }}-db-secret"
  namespace: {{ .Release.Namespace }}

type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.db.secret.password }}"