apiVersion: v1
kind: Service

metadata:
  name: "{{ .Values.appName }}-db-svc"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Values.appName }}-db-svc"

spec:
  ports:
  - port: {{ .Values.db.port.containerPort }}
    name: "{{ .Values.appName }}-db-port"
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: "{{ .Values.appName }}-db-sts-0"