apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: "{{ .Values.appName }}-db-sts"
  namespace: {{ .Release.Namespace }}

spec:
  volumeClaimTemplates:
    - metadata:
        name: "{{ .Values.appName }}-db-pvc"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "hostpath"
        resources:
          requests:
            storage: 5Gi

  serviceName: "{{ .Values.appName }}-db-svc"
  selector:
    matchLabels:
      app: "{{ .Values.appName }}-db"

  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}-db"
    spec:
      volumes:
        - name: db-init-volume
          configMap:
            name: {{ .Values.appName }}-db-init-sql
      containers:
      - image: postgres:17
        name: postgres
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: "{{ .Values.appName }}-db-secret"

        volumeMounts:
          - name: "{{ .Values.appName }}-db-pvc"
            mountPath: /var/lib/postgresql/data

          - name: db-init-volume
            mountPath: /docker-entrypoint-initdb.d/init.sql
            subPath: init.sql

        livenessProbe:
          exec:
            command:
              - "pg_isready"
              - "-U"
              - "postgres"
          initialDelaySeconds: 300
          periodSeconds: 60
          timeoutSeconds: 60

        readinessProbe:
          exec:
            command:
              - "pg_isready"
              - "-U"
              - "postgres"
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5

