apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-frontend-deploy"
  labels:
    app: "{{.Values.appName}}-frontend-deploy"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: "{{.Values.appName}}-frontend"
  strategy: {}
  template:
    metadata:
      labels:
        app: "{{.Values.appName}}-frontend"
    spec:
      containers:
      - image: "jiwon9908/transdict-ai-frontend:{{ .Chart.AppVersion }}"
        imagePullPolicy: Always
        name: "{{.Values.appName}}-frontend"
        resources: {}
        env:
        - name: REACT_APP_API_URL
          value: >-
            http://{{ .Values.backend.apiUrl | default "localhost"}}
          {{- if .Values.backend.apiPort -}}
              :{{ .Values.backend.apiPort }}
          {{- else if eq .Values.backend.port.type "NodePort" -}}
              :{{ .Values.backend.port.nodePort }}
          {{- else }}
              :{{.Values.backend.port.containerPort }}}}
          {{- end -}}