apiVersion: v1
kind: Service

metadata:
  name: "{{.Values.appName}}-backend-svc"
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: "{{.Values.appName}}-backend"

  type: {{.Values.backend.port.type}}

  ports:
    - port: {{.Values.backend.port.containerPort}}
      protocol: TCP
      targetPort: {{.Values.backend.port.containerPort}}
      {{- if eq .Values.backend.port.type "NodePort" }}
      {{- if .Values.backend.port.nodePort }}
      nodePort: {{ .Values.backend.port.nodePort }}
      {{- end }}
      {{- end }}