apiVersion: v1
kind: Secret
metadata:
  name: "{{.Values.appName}}-backend-secret"
  namespace: {{ .Release.Namespace}}
stringData:
  DB_HOST: "{{ .Values.appName}}-db-svc"
  DB_NAME: "{{.Values.db.name}}"
  DB_PASSWORD: "{{ .Values.db.secret.password }}"
  DB_PORT: "{{.Values.db.port.containerPort}}"
  DB_USER: "{{.Values.db.user}}"
  OPENAI_API_KEY: "{{.Values.backend.secret.openApiKey}}"

